"""add timepunch and approved columns to events, supervisor column to users

Revision ID: 1392e951f36
Revises: 4bd9bebcc5c
Create Date: 2016-07-19 10:50:30.200554

"""

# revision identifiers, used by Alembic.
revision = '1392e951f36'
down_revision = '4bd9bebcc5c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
