"""Initial Migration - v1

Revision ID: 14543090feb
Revises: None
Create Date: 2017-06-28 20:44:14.853437

"""

# revision identifiers, used by Alembic.
revision = "14543090feb"
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("key", sa.String(length=250), nullable=False),
        sa.Column("value", sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "passwords",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("p1", sa.String(length=128), nullable=True),
        sa.Column("p2", sa.String(length=128), nullable=True),
        sa.Column("p3", sa.String(length=128), nullable=True),
        sa.Column("p4", sa.String(length=128), nullable=True),
        sa.Column("p5", sa.String(length=128), nullable=True),
        sa.Column("last_changed", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("default", sa.Boolean(), nullable=True),
        sa.Column("permissions", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("ix_roles_default", "roles", ["default"], unique=False)
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=64), nullable=True),
        sa.Column("last_name", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=64), nullable=True),
        sa.Column("password_hash", sa.String(length=128), nullable=True),
        sa.Column("validated", sa.Boolean(), nullable=True),
        sa.Column("division", sa.String(length=128), nullable=True),
        sa.Column("login_attempts", sa.Integer(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.Column("tag_id", sa.Integer(), nullable=True),
        sa.Column("old_passwords", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["old_passwords"], ["passwords.id"]),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"]),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_index("ix_users_first_name", "users", ["first_name"], unique=False)
    op.create_index("ix_users_last_name", "users", ["last_name"], unique=False)
    op.create_table(
        "pays",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rate", sa.Float(), nullable=True),
        sa.Column("start", sa.Date(), nullable=True),
        sa.Column("end", sa.Date(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.Boolean(), nullable=True),
        sa.Column("time", sa.DateTime(), nullable=True),
        sa.Column("note", sa.String(length=120), nullable=True),
        sa.Column("ip", sa.String(length=120), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("events")
    op.drop_table("pays")
    op.drop_index("ix_users_last_name", "users")
    op.drop_index("ix_users_first_name", "users")
    op.drop_index("ix_users_email", "users")
    op.drop_table("users")
    op.drop_table("tags")
    op.drop_index("ix_roles_default", "roles")
    op.drop_table("roles")
    op.drop_table("passwords")
    op.drop_table("sessions")
    ### end Alembic commands ###
