"""eliminate backref

Revision ID: 16684792ee
Revises: f91797b14e
Create Date: 2016-07-19 15:55:56.393552

"""

# revision identifiers, used by Alembic.
revision = '16684792ee'
down_revision = 'f91797b14e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
