"""Initial Migration

Revision ID: 2a85d4c6208
Revises: None
Create Date: 2016-07-05 20:30:46.732177

"""

# revision identifiers, used by Alembic.
revision = '2a85d4c6208'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
