"""empty message

Revision ID: 38c49f0551
Revises: None
Create Date: 2016-07-05 15:49:54.495186

"""

# revision identifiers, used by Alembic.
revision = '38c49f0551'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
