"""add vacation model

Revision ID: 43f3e36b84c
Revises: 8b0d94397d
Create Date: 2017-01-12 11:22:02.039283

"""

# revision identifiers, used by Alembic.
revision = '43f3e36b84c'
down_revision = '8b0d94397d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
