"""test db

Revision ID: 46902e00afe
Revises: 54eab8516a
Create Date: 2016-07-27 10:21:54.247779

"""

# revision identifiers, used by Alembic.
revision = '46902e00afe'
down_revision = '54eab8516a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
