"""empty message

Revision ID: 4e88577cc36
Revises: 2a85d4c6208
Create Date: 2016-07-15 10:46:06.019587

"""

# revision identifiers, used by Alembic.
revision = '4e88577cc36'
down_revision = '2a85d4c6208'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'clocked_in')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clocked_in', sa.BOOLEAN(), nullable=True))
    ### end Alembic commands ###
