"""Initial Migration

Revision ID: 53c2abe8ebe
Revises: None
Create Date: 2017-06-07 16:37:38.358299

"""

# revision identifiers, used by Alembic.
revision = '53c2abe8ebe'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('key', sa.String(length=250), nullable=False),
    sa.Column('value', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    ### end Alembic commands ###
