"""Added sessions

Revision ID: 54460892ae5
Revises: 38c49f0551
Create Date: 2016-07-05 17:46:48.464454

"""

# revision identifiers, used by Alembic.
revision = '54460892ae5'
down_revision = '38c49f0551'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
