"""change one-to-many to many-to-one

Revision ID: 54eab8516a
Revises: 16684792ee
Create Date: 2016-07-19 16:00:47.141750

"""

# revision identifiers, used by Alembic.
revision = '54eab8516a'
down_revision = '16684792ee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
