"""fix supervisor reference

Revision ID: 5640887e407
Revises: 1392e951f36
Create Date: 2016-07-19 15:22:22.666640

"""

# revision identifiers, used by Alembic.
revision = '5640887e407'
down_revision = '1392e951f36'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
