"""empty message

Revision ID: 57cb9a5a9d1
Revises: 54460892ae5
Create Date: 2016-07-05 20:25:21.527057

"""

# revision identifiers, used by Alembic.
revision = '57cb9a5a9d1'
down_revision = '54460892ae5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
