"""add vacations model

Revision ID: 5a56f63ca68
Revises: 43f3e36b84c
Create Date: 2017-01-12 11:27:36.770073

"""

# revision identifiers, used by Alembic.
revision = '5a56f63ca68'
down_revision = '43f3e36b84c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacation')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacation',
    sa.Column('id', sa.INTEGER(), server_default="nextval('vacation_id_seq'::regclass)", nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='vacation_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='vacation_pkey')
    )
    ### end Alembic commands ###
