"""Add ChangeLog table to keep track of user attribute changes

Revision ID: 5b874b768e
Revises: 46902e00afe
Create Date: 2016-08-03 12:03:39.901227

"""

# revision identifiers, used by Alembic.
revision = '5b874b768e'
down_revision = '46902e00afe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
