"""empty message

Revision ID: 8b0d94397d
Revises: 2cf6de142ea
Create Date: 2017-01-09 13:05:55.103819

"""

# revision identifiers, used by Alembic.
revision = '8b0d94397d'
down_revision = '2cf6de142ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_supervisor', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_supervisor')
    ### end Alembic commands ###
