"""initial migration

Revision ID: 8ce9ccc678
Revises: None
Create Date: 2016-06-30 12:10:08.759535

"""

# revision identifiers, used by Alembic.
revision = '8ce9ccc678'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
