"""Add health screen users table

Revision ID: aeeb33115528
Revises: c31a98bb477c
Create Date: 2020-08-11 12:19:32.058487

"""

# revision identifiers, used by Alembic.
revision = 'aeeb33115528'
down_revision = 'c31a98bb477c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_screen_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('division', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('health_screen_users')
    # ### end Alembic commands ###
