"""Add health screen to db

Revision ID: c31a98bb477c
Revises: 8408e175c444
Create Date: 2020-08-02 21:50:58.437005

"""

# revision identifiers, used by Alembic.
revision = "c31a98bb477c"
down_revision = "8408e175c444"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "health_screen",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("email", sa.String(length=64), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("division", sa.String(length=128), nullable=True),
        sa.Column("questionnaire_confirmation", sa.Boolean(), nullable=False),
        sa.Column("report_to_work", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("health_screen")
    # ### end Alembic commands ###
