"""fix supervisor reference again

Revision ID: f91797b14e
Revises: 5640887e407
Create Date: 2016-07-19 15:42:04.513324

"""

# revision identifiers, used by Alembic.
revision = 'f91797b14e'
down_revision = '5640887e407'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
